[project]
name = "isometric-rpg"
version = "0.1.0"
description = "A simple isometric RPG game built with Pygame"
requires-python = ">=3.8"
dependencies = [
    "pygame==2.5.2",
    "numpy>=1.26.0",
]

[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta" 